export const FETCH_RENTALS = 'FECTH_RENTALS';
export const FETCH_RENTAL_BY_ID_SUCCESS = 'FETCH_RENTAL_BY_ID_SUCCESS';
export const FETCH_RENTAL_BY_ID_INIT = 'FETCH_RENTAL_BY_ID_INIT';
export const FECTH_RENTAL_SUCCESS = 'FECTH_RENTAL_SUCCESS';

export const FECTH_RENTALS_INIT = 'FECTH_RENTALS_INIT';
export const FECTH_RENTALS_FAIL = 'FECTH_RENTALS_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';